name: Build Youtube Clone to Azure Web App
on:
  push:
  workflow_dispatch:

env:
  NODE_VERSION: '18.x' # The NODE version to use
#  WORKING_DIRECTORY: ./src

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Use Node.js
        uses: actions/setup-node@v4
        with:
          node-version: ${{ env.NODE_VERSION }}
      - run: npm ci
      - run: npx update-browserslist-db@latest
      - run: npm run build --if-present

      - name: Zip artifact for deployment
        run: zip release.zip build -r
        
      - name: Upload artifact for deployment job
        uses: actions/upload-artifact@v3
        with:
          name: release-artifact
          path: release.zip
  
  release:
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: Download artifact
        uses: actions/download-artifact@v4
        with:
          name: release-artifact
          path: release.zip

      - name: Extarct artifact
        run: unzip release.zip
      
