name: Build Youtube Clone to Azure Web App
on:
  push:
  workflow_dispatch:

env:
  NODE_VERSION: '18.x' # The NODE version to use
#  WORKING_DIRECTORY: ./src

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: 'Cleanup build folder'
        run: |
          ls -la ./
          rm -rf ./* || true
          rm -rf ./.??* || true
          ls -la ./

      - name: Checkout code
        uses: actions/checkout@v4

      - name: Use Node.js
        uses: actions/setup-node@v4
        with:
          node-version: ${{ env.NODE_VERSION }}
      - run: |
          npm ci
          npx update-browserslist-db@latest
          npm run build --if-present
          echo "Zipping artifact for release"
          zip release.zip build -r

#     - name: Zip artifact for deployment
#      run: zip release.zip build -r
        
      - name: Upload artifact for deployment job
        uses: actions/upload-artifact@v4
        with:
          name: release-artifact
          path: release.zip
  
  release:
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: Download artifact
        uses: actions/download-artifact@v4
        with:
          name: release-artifact
         # path: release.zip

      - name: Extarct artifact
        run: unzip release.zip 
        #  mkdir ~/artifact
         
      - name: 'Cleanup build folder'
        run: |
          ls -la ./
          rm -rf ./* || true
          rm -rf ./.??* || true
          ls -la ./
      
